/* NonVoid.svelte generated by Svelte v3.9.1 */
import {
  SvelteComponent,
  assign,
  bubble,
  children,
  claim_element,
  create_slot,
  detach,
  element,
  exclude_internal_props,
  get_slot_changes,
  get_slot_context,
  get_spread_update,
  init,
  insert,
  listen,
  safe_not_equal,
  set_attributes,
  transition_in,
  transition_out
} from "svelte/internal";

function getClientNonVoid(tag) {
  function create_fragment(ctx) {
    var div, current, dispose;

    const default_slot_template = ctx.$$slots.default;
    const default_slot = create_slot(default_slot_template, ctx, null);

    var div_levels = [ctx.$$props];

    var div_data = {};
    for (var i = 0; i < div_levels.length; i += 1) {
      div_data = assign(div_data, div_levels[i]);
    }

    return {
      c() {
        div = element(tag);

        if (default_slot) default_slot.c();
        this.h();
      },

      l(nodes) {
        div = claim_element(nodes, tag.toUpperCase(), {}, false);
        var div_nodes = children(div);

        if (default_slot) default_slot.l(div_nodes);
        div_nodes.forEach(detach);
        this.h();
      },

      h() {
        set_attributes(div, div_data);
        dispose = listen(div, "click", ctx.click_handler);
      },

      m(target, anchor) {
        insert(target, div, anchor);

        if (default_slot) {
          default_slot.m(div, null);
        }

        current = true;
      },

      p(changed, ctx) {
        if (default_slot && default_slot.p && changed.$$scope) {
          default_slot.p(
            get_slot_changes(default_slot_template, ctx, changed, null),
            get_slot_context(default_slot_template, ctx, null)
          );
        }

        set_attributes(
          div,
          get_spread_update(div_levels, [changed.$$props && ctx.$$props])
        );
      },

      i(local) {
        if (current) return;
        transition_in(default_slot, local);
        current = true;
      },

      o(local) {
        transition_out(default_slot, local);
        current = false;
      },

      d(detaching) {
        if (detaching) {
          detach(div);
        }

        if (default_slot) default_slot.d(detaching);
        dispose();
      }
    };
  }

  function instance($$self, $$props, $$invalidate) {
    let { $$slots = {}, $$scope } = $$props;

    function click_handler(event) {
      bubble($$self, event);
    }

    $$self.$set = $$new_props => {
      $$invalidate(
        "$$props",
        ($$props = assign(assign({}, $$props), $$new_props))
      );
      if ("$$scope" in $$new_props)
        $$invalidate("$$scope", ($$scope = $$new_props.$$scope));
    };

    return {
      $$props,
      click_handler,
      $$props: ($$props = exclude_internal_props($$props)),
      $$slots,
      $$scope
    };
  }

  class NonVoid extends SvelteComponent {
    constructor(options) {
      super();
      init(this, options, instance, create_fragment, safe_not_equal, []);
    }
  }

  return NonVoid;
}

function getServerNonVoid(tag) {
  /* NonVoid.svelte generated by Svelte v3.9.1 */
  const { create_ssr_component, spread } = require("svelte/internal");

  const NonVoid = create_ssr_component(
    ($$result, $$props, $$bindings, $$slots) => {
      return `<${tag}${spread([$$props])}>${
        $$slots.default ? $$slots.default({}) : ``
      }</${tag}>`;
    }
  );

  return NonVoid;
}

export { getClientNonVoid, getServerNonVoid };
